# Generated by Django 5.1.1 on 2024-09-12 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id_profissional', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(default='', max_length=100)),
                ('nome_social', models.CharField(blank=True, default='', max_length=100)),
                ('profissao', models.CharField(default='', max_length=45)),
                ('endereco', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id_contato', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('contato', models.CharField(max_length=45)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lacrei.profissional')),
            ],
            options={
                'unique_together': {('profissional', 'contato')},
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateTimeField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_lacrei.profissional')),
            ],
            options={
                'unique_together': {('profissional', 'data_consulta')},
            },
        ),
    ]
